#!/bin/sh
files=$(git diff -cached -name-only -diff-filter=ACM |grep '.go$')
if [-z files]; then
exit 0
fi 
unfmtd=$(gofmt -1 $files)
if[-z unfmtd]; then
exit 0
fi echo "some .go files are not fmt d"
exit 1
